#URL for Postgres database
DB_URL: postgres://username:password@localhost:5432/server-template

#secret key for JWT
SECRET_KEY: secret

#JWT expiry in minutes
EXPIRE_MINUTES: 120
REDIS_URL: redis://localhost:6379/