services:
  postgres:
    container_name: 'template-postgres'
    image: 'postgres:latest'
    restart: always
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=server-template'
      - 'POSTGRES_PASSWORD=password'

  redis:
    container_name: 'template-redis'
    image: 'redis:latest'
    ports:
      - '6379:6379'